# Generated by Django 6.0.5 on 2026-05-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Alter the role field to include new choices
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(
                choices=[
                    ('manager', 'Property Manager'),
                    ('maintenance_staff', 'Maintenance Staff'),
                    ('resident', 'Resident'),
                ],
                max_length=20
            ),
        ),
        # Make created_by nullable to handle existing rows
        migrations.AlterField(
            model_name='maintenancetask',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_tasks',
                to='auth.user'
            ),
        ),
    ]
