# Generated by hand to bind maintenance staff to a property.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_staffprofile_and_resident_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='core.property'),
        ),
    ]