# Generated by Django 6.0.5 on 2026-05-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_residentreport_and_task_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maintenance Task', 'verbose_name_plural': 'Maintenance Tasks'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='residentprofile',
            options={'verbose_name': 'Resident Profile', 'verbose_name_plural': 'Resident Profiles'},
        ),
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Task Comment', 'verbose_name_plural': 'Task Comments'},
        ),
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task History', 'verbose_name_plural': 'Task History'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
    ]
